
import json, os
p = os.path.expanduser("~/.cache/wal/colors.json")
out = os.path.expanduser("~/.cache/wal/colors-waybar.css")

def format_color(hex_code):
    return "#" + hex_code.lstrip("#")

with open(p) as f:
    j= json.load(f)

bg = j.get("special",{}).get("background", "#000000")
fg = j.get("special",{}).get("foreground", "#ffffff")
colors = j.get("colors",{})

with open(out, "w") as f:
    f.write("#Generated by pywal\n")
    f.write(f"@define-color background {format_css_color(bg)};\n")
    f.write(f"@define-color foreground {format_css_color(fg)};\n")
    for i in range(16):
        k = f"color{i}"
        if k in colors:
            f.write(f"@define-color {k} {format_css_color(colors[k])}\n")

print("successfully generated colors-waybar.css", out)
